#!/usr/bin/env bash
# One-time bootstrap for a FRESH production server (empty .env, no
# containers running yet). Creates .env (repo root), starts the reverse
# proxy (nginx-proxy + acme-companion), then pulls and starts a GHCR-built
# n8n image via deploy.sh.
#
# This script deliberately never calls `pnpm docker:up` or `pnpm
# build:docker`, and never invokes `node` or `pnpm` at all — it only writes
# a plain-text env file and runs `docker compose`/`scripts/deploy.sh`. The
# n8n image always comes from GHCR (built by
# .github/workflows/docker-build-push.yml on GitHub's runners); this
# server never builds it locally.
#
# Usage:
#   scripts/bootstrap-production.sh --host n8n.example.com --email you@example.com --image ghcr.io/<owner>/<repo>:<sha> [--protocol https]
#
# One-time prerequisite (not done by this script): authenticate Docker to
# the private GHCR package on this machine:
#   echo "<fine-grained PAT, read:packages only>" | docker login ghcr.io -u <github-username> --password-stdin
#
# Safe to run only once per server: refuses to run if .env already
# exists, so it can't accidentally reset an existing deployment's config.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
ENV_FILE="$ROOT_DIR/.env"

HOST=""
EMAIL=""
IMAGE_REF=""
PROTOCOL="https"

usage() {
	echo "Usage: $0 --host <domain> --email <email> --image <ghcr-image-ref> [--protocol https|http]" >&2
	echo "Example: $0 --host n8n.example.com --email you@example.com --image ghcr.io/ur-code-buddy/n8n-pro:\$(git -C \"$ROOT_DIR\" rev-parse HEAD)" >&2
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--host)
		HOST="$2"
		shift 2
		;;
	--email)
		EMAIL="$2"
		shift 2
		;;
	--image)
		IMAGE_REF="$2"
		shift 2
		;;
	--protocol)
		PROTOCOL="$2"
		shift 2
		;;
	*)
		echo "Unknown argument: $1" >&2
		usage
		exit 1
		;;
	esac
done

if [[ -z "$HOST" || -z "$EMAIL" || -z "$IMAGE_REF" ]]; then
	usage
	exit 1
fi

if [[ "$PROTOCOL" != "https" && "$PROTOCOL" != "http" ]]; then
	echo "Error: --protocol must be 'https' or 'http', got: $PROTOCOL" >&2
	exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
	echo "Error: $ENV_FILE already exists — this script is for a FRESH server only." >&2
	echo "To change settings, edit $ENV_FILE by hand. To deploy a new image, use scripts/deploy.sh <image-ref>." >&2
	exit 1
fi

echo "INFO: Writing $ENV_FILE..."
{
	echo "# Generated by: scripts/bootstrap-production.sh (production bootstrap)"
	echo "# This file is NOT managed by 'pnpm docker:up' on this server. Edit by hand,"
	echo "# or use scripts/deploy.sh to change N8N_IMAGE."
	echo ""
	echo "WEBHOOK_URL=${PROTOCOL}://${HOST}/"
	echo "N8N_EDITOR_BASE_URL=${PROTOCOL}://${HOST}"
	echo "N8N_PROTOCOL=${PROTOCOL}"
	echo "N8N_HOST=${HOST}"
	echo "LETSENCRYPT_EMAIL=${EMAIL}"
	echo "N8N_LICENSE_UNLOCK_ALL=true"
	echo "N8N_DEFAULT_OWNER_ENABLED=true"
	echo "N8N_DEFAULT_OWNER_EMAIL=baivab@admin.local"
	echo "N8N_DEFAULT_OWNER_PASSWORD=admin@ccess4321"
	if [[ "$PROTOCOL" == "https" ]]; then
		echo "N8N_SECURE_COOKIE=true"
	fi
	echo "N8N_IMAGE=${IMAGE_REF}"
} >"$ENV_FILE"

echo "INFO: Starting reverse proxy (nginx-proxy + acme-companion only — n8n image is not touched)..."
docker compose -f "$COMPOSE_FILE" up -d nginx-proxy acme-companion

echo "INFO: Pulling and starting n8n via scripts/deploy.sh..."
"$SCRIPT_DIR/deploy.sh" "$IMAGE_REF"
