#!/usr/bin/env node
/**
 * Build (if needed) and run n8n in Docker detached mode.
 *
 * Usage:
 *   pnpm docker:up <webhook-url> [--build]
 *   WEBHOOK_URL=https://n8n.example.com pnpm docker:up
 */

import { $, echo, chalk, fs } from 'zx';
import path from 'path';
import { fileURLToPath } from 'url';

$.verbose = false;
process.env.FORCE_COLOR = '1';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');
const dockerDir = path.join(rootDir, 'docker');
const composeFile = path.join(dockerDir, 'docker-compose.yml');
const envFile = path.join(dockerDir, '.env');
const imageName = 'n8nio/n8n:local';

const FORK_DEFAULTS = {
	N8N_LICENSE_UNLOCK_ALL: 'true',
	N8N_DEFAULT_OWNER_ENABLED: 'true',
	N8N_DEFAULT_OWNER_EMAIL: 'baivab@admin.local',
	N8N_DEFAULT_OWNER_PASSWORD: 'admin@ccess4321',
};

async function commandExists(command) {
	try {
		await $`command -v ${command}`;
		return true;
	} catch {
		return false;
	}
}

async function checkPrerequisites() {
	const missing = [];
	for (const cmd of ['docker', 'node', 'pnpm']) {
		if (!(await commandExists(cmd))) missing.push(cmd);
	}
	if (missing.length > 0) {
		echo(chalk.red(`Error: missing required tools: ${missing.join(', ')}`));
		process.exit(1);
	}
}

function parseArgs(argv) {
	const forceBuild = argv.includes('--build');
	const positional = argv.filter((arg) => !arg.startsWith('-'));
	return { forceBuild, webhookUrl: positional[0] ?? process.env.WEBHOOK_URL };
}

/**
 * @param {string} rawUrl
 */
function parseWebhookUrl(rawUrl) {
	let parsed;
	try {
		parsed = new URL(rawUrl);
	} catch {
		echo(chalk.red(`Error: invalid webhook URL: ${rawUrl}`));
		process.exit(1);
	}

	if (!parsed.protocol || parsed.protocol === 'file:') {
		echo(chalk.red('Error: webhook URL must include a protocol (http:// or https://)'));
		process.exit(1);
	}

	const origin = parsed.origin;
	const webhookUrl = origin.endsWith('/') ? origin : `${origin}/`;
	const editorBaseUrl = origin.replace(/\/$/, '');
	const isHttps = parsed.protocol === 'https:';

	/** @type {Record<string, string>} */
	const env = {
		WEBHOOK_URL: webhookUrl,
		N8N_EDITOR_BASE_URL: editorBaseUrl,
		N8N_PROTOCOL: parsed.protocol.replace(':', ''),
		N8N_HOST: parsed.hostname,
		...FORK_DEFAULTS,
	};

	if (isHttps) {
		env.N8N_SECURE_COOKIE = 'true';
	}

	if (
		(parsed.protocol === 'http:' && parsed.port && parsed.port !== '80') ||
		(parsed.protocol === 'https:' && parsed.port && parsed.port !== '443')
	) {
		env.N8N_PORT = parsed.port;
	}

	return { webhookUrl, editorBaseUrl, env };
}

/**
 * @param {Record<string, string>} env
 */
async function writeEnvFile(env) {
	const lines = [
		'# Generated by: pnpm docker:up <webhook-url>',
		'# Re-run docker:up to update WEBHOOK_URL-derived values.',
		'',
		...Object.entries(env).map(([key, value]) => `${key}=${value}`),
		'',
	];
	await fs.writeFile(envFile, lines.join('\n'));
}

async function imageExists() {
	try {
		await $`docker image inspect ${imageName}`;
		return true;
	} catch {
		return false;
	}
}

async function buildImage() {
	echo(chalk.yellow(`INFO: Building ${imageName} (this can take 20–40+ minutes on first run)...`));
	const buildProcess = $`cd ${rootDir} && pnpm build:docker`;
	buildProcess.pipe(process.stdout);
	await buildProcess;
}

async function composeUp() {
	await $`docker compose -f ${composeFile} up -d`;
}

function printSummary({ editorBaseUrl, webhookUrl }) {
	echo('');
	echo(chalk.green.bold('═'.repeat(54)));
	echo(chalk.green.bold('           n8n is running (detached)'));
	echo(chalk.green.bold('═'.repeat(54)));
	echo(`  Editor:     ${editorBaseUrl}`);
	echo(`  Webhooks:   ${webhookUrl}`);
	echo(`  Local port: http://localhost:5678`);
	echo('');
	echo(`  Login:      ${FORK_DEFAULTS.N8N_DEFAULT_OWNER_EMAIL}`);
	echo(`  Password:   ${FORK_DEFAULTS.N8N_DEFAULT_OWNER_PASSWORD}`);
	echo('');
	echo(chalk.yellow('  Production: use TLS via a reverse proxy, change the default password,'));
	echo(chalk.yellow('  and keep the n8n_data volume backed up (encryption key lives there).'));
	echo('');
	echo('  Logs:   pnpm docker:logs');
	echo('  Stop:   pnpm docker:down');
	echo(chalk.green.bold('═'.repeat(54)));
	echo('');
}

async function main() {
	const { forceBuild, webhookUrl: rawWebhookUrl } = parseArgs(process.argv.slice(2));

	if (!rawWebhookUrl) {
		echo(chalk.red('Error: webhook URL is required'));
		echo('');
		echo('Usage:');
		echo('  pnpm docker:up <webhook-url> [--build]');
		echo('  WEBHOOK_URL=https://n8n.example.com pnpm docker:up');
		echo('');
		echo('Example:');
		echo('  pnpm docker:up https://n8n.yourdomain.com');
		process.exit(1);
	}

	await checkPrerequisites();

	const { webhookUrl, editorBaseUrl, env } = parseWebhookUrl(rawWebhookUrl);
	await writeEnvFile(env);

	const hasImage = await imageExists();
	if (forceBuild || !hasImage) {
		if (!hasImage) {
			echo(chalk.yellow(`INFO: Image ${imageName} not found — building...`));
		} else {
			echo(chalk.yellow(`INFO: Rebuilding ${imageName} (--build)...`));
		}
		await buildImage();
	} else {
		echo(chalk.green(`INFO: Using existing image ${imageName}`));
	}

	echo(chalk.yellow('INFO: Starting n8n with docker compose (detached)...'));
	await composeUp();
	printSummary({ editorBaseUrl, webhookUrl });
}

main().catch((error) => {
	echo(chalk.red(`Unexpected error: ${error.message}`));
	process.exit(1);
});
